import type { Metadata } from "next";

export const metadataSettings: Metadata = {
  title: {
    template: "%s | Gathbook",
    default: "Gathbook",
  },
  description: "Generated by create next app",
};
